/**
 * regenerate-stale-docs — Seed-pack SKIP_TYPES filter unit tests
 *
 * Validates the SKIP_TYPES=['nec','canon'] filter logic added in commit e7b6c9e.
 * Seed-pack documents (NEC, Canon) are auto-generated by the development
 * pipeline and must be excluded from manual stale regeneration.
 *
 * Edge cases covered:
 *  1. All seed-pack docs → early return, all skipped
 *  2. Mixed seed-pack + non-seed-pack → only seed-pack removed
 *  3. No seed-pack docs → all preserved
 *  4. Single seed-pack doc → removed
 *  5. Empty input → empty filtered array
 *  6. Duplicate docTypes → all duplicates handled
 *  7. All-skipped early return response structure
 *  8. The actual SKIP_TYPES array value (guard against accidental changes)
 */

import { assertEquals, assert } from "https://deno.land/std@0.168.0/testing/asserts.ts";

// ═══════════════════════════════════════════════════════════════
// Pure function mirror of the logic in index.ts (lines 49-72)
// ═══════════════════════════════════════════════════════════════

const SKIP_TYPES = ['nec', 'canon'];

function filterSeedPackDocTypes(docTypes: string[]): string[] {
  return docTypes.filter((dt) => !SKIP_TYPES.includes(dt));
}

function buildAllSkippedResponse(docTypes: string[]) {
  return {
    success: true,
    regenerated: [],
    errors: [],
    total: docTypes.length,
    succeeded: 0,
    failed: 0,
    skipped: docTypes.length,
    message: "All requested docTypes are seed-pack docs — nothing to regenerate",
  };
}

// ═══════════════════════════════════════════════════════════════
// Tests
// ═══════════════════════════════════════════════════════════════

Deno.test({
  name: "filter: all seed-pack docs (nec + canon) returns empty array",
  fn() {
    assertEquals(filterSeedPackDocTypes(['nec', 'canon']), []);
  },
});

Deno.test({
  name: "filter: mixed seed-pack and non-seed-pack removes only seed-pack",
  fn() {
    const result = filterSeedPackDocTypes(['nec', 'story_outline']);
    assertEquals(result, ['story_outline']);
  },
});

Deno.test({
  name: "filter: three-way mix with nec, canon, and project_overview",
  fn() {
    const result = filterSeedPackDocTypes(['nec', 'canon', 'project_overview']);
    assertEquals(result, ['project_overview']);
  },
});

Deno.test({
  name: "filter: no seed-pack docs returns all unchanged",
  fn() {
    const input = ['story_outline', 'concept_brief', 'treatment'];
    assertEquals(filterSeedPackDocTypes(input), input);
  },
});

Deno.test({
  name: "filter: single seed-pack doc (nec) returns empty",
  fn() {
    assertEquals(filterSeedPackDocTypes(['nec']), []);
  },
});

Deno.test({
  name: "filter: single seed-pack doc (canon) returns empty",
  fn() {
    assertEquals(filterSeedPackDocTypes(['canon']), []);
  },
});

Deno.test({
  name: "filter: empty array returns empty array",
  fn() {
    assertEquals(filterSeedPackDocTypes([]), []);
  },
});

Deno.test({
  name: "filter: duplicates of seed-pack types are all removed",
  fn() {
    assertEquals(filterSeedPackDocTypes(['nec', 'nec', 'canon']), []);
  },
});

Deno.test({
  name: "filter: duplicate non-seed-pack doc preserved once",
  fn() {
    const result = filterSeedPackDocTypes(['story_outline', 'story_outline']);
    assertEquals(result, ['story_outline', 'story_outline']);
  },
});

Deno.test({
  name: "filter: seed-pack with other doc types — only seed-pack removed in order",
  fn() {
    const result = filterSeedPackDocTypes(['canon', 'treatment', 'nec', 'script']);
    assertEquals(result, ['treatment', 'script']);
  },
});

Deno.test({
  name: "early-return: all-skipped response has correct structure and values",
  fn() {
    const docTypes = ['nec', 'canon'];
    const filtered = filterSeedPackDocTypes(docTypes);
    const response = buildAllSkippedResponse(docTypes);

    assertEquals(response.success, true);
    assertEquals(response.regenerated.length, 0);
    assertEquals(response.errors.length, 0);
    assertEquals(response.total, 2);
    assertEquals(response.succeeded, 0);
    assertEquals(response.failed, 0);
    assertEquals(response.skipped, 2);
    assert(typeof response.message === 'string');
    assert(response.message.includes('seed-pack'));
  },
});

Deno.test({
  name: "early-return: single seed-pack doc still produces correct response",
  fn() {
    const docTypes = ['canon'];
    const response = buildAllSkippedResponse(docTypes);

    assertEquals(response.total, 1);
    assertEquals(response.skipped, 1);
    assertEquals(response.succeeded, 0);
  },
});

Deno.test({
  name: "SKIP_TYPES: value guard — array must contain exactly nec and canon",
  fn() {
    assertEquals(SKIP_TYPES, ['nec', 'canon']);
    assertEquals(SKIP_TYPES.length, 2);
  },
});