import { useState, useMemo, useEffect } from 'react';
import { Zap, Loader2, X, FileText, CheckCircle2, Circle, AlertCircle } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { useReverseEngineer } from '@/hooks/useReverseEngineer';
import { useQueryClient } from '@tanstack/react-query';
import { toast } from 'sonner';
const BASE_DOC_ROWS: Array<{ key: string; label: string; icon: typeof FileText }> = [
  { key: 'concept_brief',   label: 'Concept Brief',    icon: FileText },
  { key: 'market_sheet',    label: 'Market Sheet',     icon: FileText },
  { key: 'format_rules',    label: 'Format Rules',     icon: FileText },
  { key: 'character_bible', label: 'Character Bible',   icon: FileText },
  { key: 'beat_sheet',      label: 'Beat Sheet',        icon: FileText },
  { key: 'treatment',       label: 'Treatment',        icon: FileText },
  { key: 'story_outline',   label: 'Story Outline',    icon: FileText },
  { key: 'idea',            label: 'Idea',              icon: FileText },
];

type DocState = 'pending' | 'running' | 'done' | 'error';

interface ReverseEngineerCalloutProps {
  projectId: string;
  documents: any[];
}

export function ReverseEngineerCallout({ projectId, documents }: ReverseEngineerCalloutProps) {
  // BASE_DOC_ROWS is the canonical list of foundation docs generated by reverse-engineer-script.
  // Do not append dynamic items — BASE_DOC_ROWS already covers all pipeline outputs.
  const docRows = BASE_DOC_ROWS;

  const [dismissed, setDismissed] = useState(false);
  const { reverseEngineerFromScript, isRunning, currentJob } = useReverseEngineer();
  const queryClient = useQueryClient();

  const scriptDoc = useMemo(() =>
    documents.find(d => {
      const dt = (d.doc_type || '') as string;
      const role = (d.doc_role || '') as string;
      const title = (d.title || '') as string;
      if (dt.includes('script')) return true;
      if (dt === 'source_script') return true;
      if (role === 'source_script') return true;
      if (role === 'creative_primary' && title.toLowerCase().includes('script')) return true;
      return false;
    }), [documents]);

  const hasConceptBrief = useMemo(() =>
    documents.some(d => d.doc_type === 'concept_brief'), [documents]);

  if (dismissed || !scriptDoc || hasConceptBrief) return null;

  // Map job stages to doc rows for live progress display
  // structure_1/2/3 + synthesise → concept_brief; beat_sheet → beat_sheet; character_bible → character_bible; storing_docs → market_sheet
  const STAGE_ORDER = ['structure_1', 'structure_2', 'structure_3', 'synthesise', 'idea', 'beat_sheet', 'character_bible', 'treatment', 'story_outline', 'market_sheet', 'infer_criteria', 'storing_docs'];
  const stageToDocKey: Record<string, string> = {
    structure_1:     'concept_brief',
    structure_2:     'concept_brief',
    structure_3:     'concept_brief',
    synthesise:      'concept_brief',
    idea:            'idea',
    beat_sheet:      'beat_sheet',
    character_bible: 'character_bible',
    treatment:       'treatment',
    story_outline:   'story_outline',
    market_sheet:    'market_sheet',
    infer_criteria: 'market_sheet',
    storing_docs:    'market_sheet',
  };

  const getDocState = (docKey: string): DocState => {
    if (!currentJob) return 'pending';
    if (currentJob.status === 'done') return 'done';
    if (currentJob.status === 'error') {
      const errStage = Object.entries(currentJob.stages || {}).find(([, s]) => s.status === 'error');
      if (errStage) return 'error';
      return 'done';
    }
    const currentStage = currentJob.current_stage;
    const stageForDoc = stageToDocKey[currentStage];
    if (stageForDoc === docKey) return 'running';
    const docStageIndex = STAGE_ORDER.indexOf(
      Object.entries(stageToDocKey).find(([, dk]) => dk === docKey)?.[0] ?? ''
    );
    const currentIndex = STAGE_ORDER.indexOf(currentStage);
    // A doc is done if ALL stages that produce it are done
    const stagesForThisDoc = STAGE_ORDER.filter(s => stageToDocKey[s] === docKey);
    const allDone = stagesForThisDoc.every(s => currentJob.stages?.[s]?.status === 'done');
    if (allDone) return 'done';
    const anyRunning = stagesForThisDoc.some(s => currentJob.stages?.[s]?.status === 'running');
    if (anyRunning) return 'running';
    if (docStageIndex < currentIndex) return 'done';
    if (docStageIndex > currentIndex) return 'pending';
    return 'pending';
  };

  const handleGenerate = async () => {
    try {
      const { job_id } = await reverseEngineerFromScript(projectId, scriptDoc.id);
      toast.success("Reverse-engineering started — you'll see live progress below");
    } catch (e: any) {
      toast.error(e?.message || 'Could not start reverse-engineering');
    }
  };

  const handleDismiss = () => {
    setDismissed(true);
    if (currentJob?.status === 'done') {
      queryClient.invalidateQueries({ queryKey: ['dev-v2-docs', projectId] });
      queryClient.invalidateQueries({ queryKey: ['seed-pack-versions', projectId] });
      queryClient.invalidateQueries({ queryKey: ['project-documents', projectId] });
    }
  };

  const isDone = currentJob?.status === 'done';
  const isError = currentJob?.status === 'error';
  const totalStages = Object.keys(currentJob?.stages || {}).length;
  const doneStages = Object.values(currentJob?.stages || {}).filter(s => s.status === 'done').length;
  const progressPct = totalStages > 0 ? (doneStages / totalStages) * 100 : 0;

  return (
    <div className="relative rounded-lg border border-amber-500/30 bg-amber-500/5 p-4 mb-4">
      <button
        onClick={() => setDismissed(true)}
        className="absolute top-2 right-2 p-1 rounded text-muted-foreground hover:text-foreground transition-colors"
        aria-label="Dismiss"
      >
        <X className="h-3.5 w-3.5" />
      </button>

      <div className="flex items-start gap-3">
        <div className="rounded-md bg-amber-500/10 p-2 shrink-0">
          <Zap className="h-4 w-4 text-amber-500" />
        </div>
        <div className="min-w-0 flex-1">
          <h4 className="text-sm font-medium text-foreground mb-1">
            {isDone ? '✅ Reverse-engineering complete!' : isError ? '⚠️ Reverse-engineering failed' : 'Script detected — generate full pipeline?'}
          </h4>
          <p className="text-xs text-muted-foreground mb-3 leading-relaxed">
            {isRunning || isDone
              ? `${docRows.length} foundation documents generated from your script.`
              : `Generate ${docRows.map(d => d.label).join(', ')} from your script in one click.`}
          </p>

          {/* Live stage progress */}
          {(isRunning || isDone || isError) && (
            <div className="rounded-md border border-amber-500/30 bg-amber-500/10 px-3 py-2.5 mb-3 space-y-2">
              {/* Current stage label */}
              <div className="flex items-center gap-2">
                {isError ? (
                  <AlertCircle className="h-3.5 w-3.5 text-red-400 shrink-0" />
                ) : isDone ? (
                  <CheckCircle2 className="h-3.5 w-3.5 text-emerald-500 shrink-0" />
                ) : (
                  <Loader2 className="h-3.5 w-3.5 animate-spin text-amber-500 shrink-0" />
                )}
                <span className="text-[11px] text-amber-400 font-medium">
                  {isError
                    ? (currentJob?.error ?? 'An error occurred')
                    : isDone
                    ? 'All documents generated!'
                    : (currentJob?.stages?.[currentJob.current_stage]?.label ?? 'Working…')}
                </span>
              </div>

              {/* Per-doc progress rows */}
              <div className="space-y-1 pl-1">
                {docRows.map(doc => {
                  const Icon = doc.icon;
                  const state = getDocState(doc.key);
                  return (
                    <div key={doc.key} className="flex items-center gap-2 text-[11px]">
                      <div className="shrink-0 w-4 h-4 flex items-center justify-center">
                        {state === 'done' ? (
                          <CheckCircle2 className="h-3.5 w-3.5 text-emerald-500" />
                        ) : state === 'running' ? (
                          <Loader2 className="h-3.5 w-3.5 animate-spin text-amber-500" />
                        ) : state === 'error' ? (
                          <AlertCircle className="h-3.5 w-3.5 text-red-400" />
                        ) : (
                          <Circle className="h-3 w-3 text-muted-foreground/40" />
                        )}
                      </div>
                      <Icon className={`h-3 w-3 shrink-0 ${state === 'done' ? 'text-emerald-500/70' : state === 'running' ? 'text-amber-500' : 'text-muted-foreground/40'}`} />
                      <span className={state === 'done' ? 'text-foreground/60' : state === 'running' ? 'text-foreground font-medium' : 'text-muted-foreground/50'}>
                        {doc.label}
                      </span>
                      {state === 'done' && <span className="ml-auto text-[9px] text-emerald-500/80 font-medium pr-1">Done</span>}
                      {state === 'running' && <span className="ml-auto text-[9px] text-amber-400/70 animate-pulse pr-1">Working…</span>}
                      {state === 'error' && <span className="ml-auto text-[9px] text-red-400/80 pr-1">Failed</span>}
                    </div>
                  );
                })}
              </div>

              {/* Progress bar */}
              <div className="relative h-0.5 rounded-full bg-amber-900/40 overflow-hidden mt-1">
                <div
                  className={`absolute inset-y-0 left-0 rounded-full transition-all duration-700 ${
                    isError ? 'bg-red-400' : isDone ? 'bg-emerald-500' : 'bg-amber-500'
                  }`}
                  style={{ width: `${progressPct}%` }}
                />
              </div>
            </div>
          )}

          <div className="flex gap-2">
            <Button
              size="sm"
              className="h-8 text-xs gap-1.5 bg-amber-600 hover:bg-amber-700 text-foreground border-0"
              disabled={isRunning}
              onClick={handleGenerate}
            >
              {isRunning ? <Loader2 className="h-3 w-3 animate-spin" /> : <Zap className="h-3 w-3" />}
              {isRunning ? 'Generating…' : 'Generate Pipeline Documents'}
            </Button>
            {(isDone || isError) && (
              <Button size="sm" variant="outline" className="h-8 text-xs" onClick={handleDismiss}>
                {isDone ? 'View Documents →' : 'Dismiss'}
              </Button>
            )}
          </div>
        </div>
      </div>
    </div>
  );
}
