/**
 * Tests for: NEC canonical format mismatch — regenerate 500 fix
 *
 * Commit e7b6c9e — 2 changes:
 *   1. Edge function: regenerate-stale-docs SKIP_TYPES filter (tested in Deno)
 *   2. Frontend: NEC toast message updated in ProjectDevelopmentEngine.tsx
 *
 * Test approach: static analysis of the toast message text
 */

import { describe, it, expect } from 'vitest';

const ENG_PATH = '/Users/laralane/code/iffy/src/pages/ProjectDevelopmentEngine.tsx';

// ════════════════════════════════════════════════════════════════════════════════
// FIX: NEC toast message updated for seed-pack regeneration behavior
// ════════════════════════════════════════════════════════════════════════════════

describe('Fix — NEC regenerate toast message', () => {

  it('NEC toast message explains auto-generation by pipeline', async () => {
    const fs = await import('fs');
    const src = fs.readFileSync(ENG_PATH, 'utf-8');

    // The NEC toast at line 1207 should explain pipeline auto-generation
    expect(src).toContain('NEC is auto-generated by the development pipeline');
  });

  it('NEC toast message mentions automatic regeneration on qualification changes', async () => {
    const fs = await import('fs');
    const src = fs.readFileSync(ENG_PATH, 'utf-8');

    // The message should explain that changes to qualifications trigger auto-regeneration
    expect(src).toContain('Changes to qualifications trigger automatic regeneration');
  });

  it('NEC toast message says cannot be manually regenerated', async () => {
    const fs = await import('fs');
    const src = fs.readFileSync(ENG_PATH, 'utf-8');

    // Must make it clear manual regeneration is not available for NEC
    expect(src).toContain('cannot be manually regenerated');
  });

  it('NEC toast message is the only seed-pack toast (no separate CANON toast)', async () => {
    const fs = await import('fs');
    const src = fs.readFileSync(ENG_PATH, 'utf-8');

    // The frontend only checks for 'nec' in handleStaleRegenerate — canon is handled
    // server-side in regenerate-stale-docs only
    const necCheckLine = src.split('\n').find(l => l.includes("doc_type === 'nec'"));
    expect(necCheckLine).toBeDefined();

    // There should NOT be a separate `doc_type === 'canon'` check in handleStaleRegenerate
    const canonHandleLines = src.split('\n').filter(l =>
      l.includes("doc_type === 'canon'") && l.includes('handleStaleRegenerate')
    );
    expect(canonHandleLines.length).toBe(0);
  });

  it('non-seed-pack docs still reach the generate-document API call (no regression)', async () => {
    const fs = await import('fs');
    const src = fs.readFileSync(ENG_PATH, 'utf-8');

    // The general else branch (non-idea, non-treatment, non-nec) should still
    // invoke generate-document — verify the supabase.functions.invoke call exists
    // after the NEC block
    const lines = src.split('\n');
    const necBlockEnd = lines.findLastIndex(l => l.includes("doc_type === 'nec'"));
    const afterNec = lines.slice(necBlockEnd);

    // There should be an 'else' block after the NEC check
    const elseBlock = afterNec.find(l => l.trim() === '} else {');
    expect(elseBlock).toBeDefined();

    // The else block should contain supabase.functions.invoke('generate-document', ...)
    const invokeLine = afterNec.find(l => l.includes("supabase.functions.invoke"));
    expect(invokeLine).toBeDefined();
    expect(invokeLine).toContain('generate-document');
  });

  it('NEC check returns early after toast (no API call for NEC)', async () => {
    const fs = await import('fs');
    const src = fs.readFileSync(ENG_PATH, 'utf-8');

    // The NEC block should have a return statement immediately after the toast
    const lines = src.split('\n');
    for (let i = 0; i < lines.length; i++) {
      if (lines[i].includes("doc_type === 'nec'")) {
        // Check there's a `return` within a few lines after
        let foundReturn = false;
        for (let j = i; j <= i + 3 && j < lines.length; j++) {
          if (lines[j].includes('return')) {
            foundReturn = true;
            break;
          }
        }
        expect(foundReturn).toBe(true);
      }
    }
  });

});