/**
 * convergence-coach-engine
 *
 * Phase 2.1 — Convergence Coaching Engine (Pass 1)
 *
 * Diagnoses convergence between narrative documents and canonical scene/entity state.
 * Two axes: Narrative Structure + Feasibility.
 *
 * NO AI — purely deterministic structural comparisons.
 */

import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";

/* ─────────────────────────────────────────────────────────────────
   Types
   ───────────────────────────────────────────────────────────────── */

interface NarrativeStructureFinding {
  checkId: string;
  severity: "critical" | "high" | "medium" | "low";
  upstreamDoc: string;
  downstreamDoc: string;
  description: string;
  divergenceType: "omission" | "contradiction" | "expansion" | "silence";
  affectedElements: string[];
}

interface FeasibilityFinding {
  checkId: string;
  severity: "critical" | "high" | "medium" | "low";
  entityOrSystem: string;
  description: string;
  expected: string;
  actual: string;
}

interface Blocker {
  axis: "narrative_structure" | "feasibility";
  description: string;
  upstreamSource: string;
  cannotFixWithout: string;
}

interface FixableIssue {
  axis: "narrative_structure" | "feasibility";
  description: string;
  fixBy: "regenerate_beat_sheet" | "regenerate_feature_script" | "rerun_entity_links" | "regenerate_story_outline";
  estimatedEffort: "low" | "medium" | "high";
}

interface RevisionPrescription {
  axis: "narrative_structure" | "feasibility";
  priority: number;
  prescription: string;
  whyItMatters: string;
  upstreamChange: string | null;
  /** Scene-anchored prescription generated by LLM — higher leverage, specific to scene content. */
  scene_prescription?: string;
  /** Estimated GP impact (0–20 scale) for applying this prescription */
  estimated_gp_impact?: number;
}

interface ConvergenceDiagnostic {
  projectId: string;
  generatedAt: string;
  narrativeStructureAxis: {
    status: "converged" | "diverged" | "unknown";
    score: number;
    findings: NarrativeStructureFinding[];
  };
  feasibilityAxis: {
    status: "converged" | "diverged" | "unknown";
    score: number;
    findings: FeasibilityFinding[];
  };
  convergenceTrajectory: {
    trend: "improving" | "stable" | "degrading" | "unknown";
    trendReason: string;
    blockers: Blocker[];
    fixable: FixableIssue[];
  };
  revisionPrescriptions: RevisionPrescription[];
}

/* ─────────────────────────────────────────────────────────────────
   Helpers
   ───────────────────────────────────────────────────────────────── */

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers":
    "authorization, x-client-info, apikey, content-type",
};

/** Extract uppercase normalised key entities from a text string. */
function extractKeyEntities(text: string): string[] {
  if (!text) return [];
  const words = text.toUpperCase().match(/[A-Z][A-Z0-9]+/g) || [];
  // Filter out stopwords
  const stop = new Set(["THE", "AND", "FOR", "WITH", "FROM", "INTO", "INTO", "IN", "ON", "AT", "TO", "OF", "A", "AN", "IS", "ARE", "WAS", "WERE", "BE", "BY", "AS", "THAT", "THIS", "BUT", "OR", "NOT", "THEY", "THEM", "HAVE", "HAS", "HAD", "ITS", "IT", "HE", "SHE", "WE", "YOU", "HIS", "HER", "THEIR", "THAN", "THEN", "SO", "WHEN", "WHERE", "WHICH", "WHO", "WHAT", "WHY", "HOW", "ALL", "EACH", "BOTH", "FEW", "MORE", "MOST", "OTHER", "SOME", "SUCH", "ONLY", "OWN", "SAME", "VERY", "JUST", "ALSO", "NOW", "HERE", "THERE", "CAN", "WILL", "JUST", "JUST"]);
  return [...new Set(words.filter(w => w.length > 2 && !stop.has(w)))];
}

/** Count occurrences of each string in an array. */
function countOccurrences(arr: string[]): Record<string, number> {
  const counts: Record<string, number> = {};
  for (const v of arr) {
    counts[v] = (counts[v] || 0) + 1;
  }
  return counts;
}

/** Score a findings array — 1.0 = no findings, decreases with severity. */
function scoreFindings(findings: Array<{ severity: string }>): number {
  if (findings.length === 0) return 1.0;
  const weight: Record<string, number> = { critical: 0.3, high: 0.6, medium: 0.8, low: 0.95 };
  const total = findings.reduce((acc, f) => acc + (weight[f.severity] ?? 0.7), 0);
  return Math.max(0, 1 - (total / findings.length) * 0.1);
}

/** Extract structured content from a project_document_version.
 * meta_json is the primary store (JSONB).
 * plaintext also contains JSON for reverse-engineered docs.
 */
function extractDocContent(version: any): any {
  if (!version) return null;
  // meta_json is a JSONB field — supabase returns it as an object already
  if (version.meta_json && typeof version.meta_json === 'object') {
    return version.meta_json;
  }
  // plaintext contains JSON for reverse-engineered documents (e.g. beat_sheet, story_outline)
  if (version.plaintext) {
    try {
      return JSON.parse(version.plaintext);
    } catch {
      return null;
    }
  }
  return null;
}

/** Fetch latest is_current version for a doc type in a project. */
async function fetchLatestDocVersion(
  supabase: any,
  projectId: string,
  docType: string
): Promise<any | null> {
  // 1. Get the project_document record
  const { data: doc } = await supabase
    .from("project_documents")
    .select("id")
    .eq("project_id", projectId)
    .eq("doc_type", docType)
    .maybeSingle();

  if (!doc) return null;

  // 2. Get the latest is_current version
  const { data: version } = await supabase
    .from("project_document_versions")
    .select("*")
    .eq("document_id", doc.id)
    .eq("is_current", true)
    .maybeSingle();

  return version || null;
}

/** Fetch latest scene graph for a project.
 * Uses the Supabase REST API via direct fetch (bypasses potential Edge Runtime supabase client quirks).
 */
async function fetchSceneGraph(supabaseUrl: string, serviceRoleKey: string, projectId: string): Promise<any | null> {
  try {
    const headers = {
      "apikey": serviceRoleKey,
      "Authorization": `Bearer ${serviceRoleKey}`,
      "Content-Type": "application/json",
    };

    // Get all scenes for this project
    const scenesUrl = `${supabaseUrl}/rest/v1/scene_graph_scenes?project_id=eq.${projectId}&select=id,scene_key&order=scene_key.asc`;
    const scenesRes = await fetch(scenesUrl, { headers });
    if (!scenesRes.ok) return null;
    const scenes: Array<{ id: string; scene_key: string }> = await scenesRes.json();
    if (!scenes || scenes.length === 0) return null;

    const sceneIds = scenes.map(s => s.id);

    // Get all draft versions for these scenes
    // Filter by status='draft' and get latest version per scene using max(version_number)
    const versionsUrl = `${supabaseUrl}/rest/v1/scene_graph_versions?project_id=eq.${projectId}&status=eq.draft&scene_id=in.(${sceneIds.join(",")})&select=scene_id,slugline,location,time_of_day,characters_present,content,version_number&order=version_number.desc`;
    const versionsRes = await fetch(versionsUrl, { headers });
    if (!versionsRes.ok) return null;
    const versions: Array<any> = await versionsRes.json();
    if (!versions || versions.length === 0) return null;

    // Deduplicate: keep first (highest version_number) per scene_id
    const versionMap = new Map<string, any>();
    for (const v of versions) {
      if (!versionMap.has(v.scene_id)) {
        versionMap.set(v.scene_id, v);
      }
    }

    const mergedScenes = scenes
      .map(s => {
        const v = versionMap.get(s.id);
        return {
          scene_key: s.scene_key,
          slugline: v?.slugline || "",
          location: v?.location || "",
          time_of_day: v?.time_of_day || "",
          characters_present: v?.characters_present || [],
          content: v?.content || "",
        };
      })
      .filter(s => s.slugline || s.content);

    return { scenes: mergedScenes };
  } catch {
    return null;
  }
}

/** Fetch narrative_entities for a project via REST API (bypasses supabase client field-mapping quirks). */
async function fetchNarrativeEntities(supabaseUrl: string, serviceRoleKey: string, projectId: string): Promise<any[]> {
  try {
    const headers = {
      "apikey": serviceRoleKey,
      "Authorization": `Bearer ${serviceRoleKey}`,
      "Content-Type": "application/json",
    };
    const url = `${supabaseUrl}/rest/v1/narrative_entities?project_id=eq.${projectId}&select=id,canonical_name,entity_type,scene_count`;
    const res = await fetch(url, { headers });
    if (!res.ok) return [];
    const data = await res.json();
    return Array.isArray(data) ? data : [];
  } catch {
    return [];
  }
}

/** Fetch narrative_scene_entity_links for a project via REST API (bypasses supabase client quirks). */
async function fetchEntityLinks(supabaseUrl: string, serviceRoleKey: string, projectId: string): Promise<any[]> {
  try {
    const headers = {
      "apikey": serviceRoleKey,
      "Authorization": `Bearer ${serviceRoleKey}`,
      "Content-Type": "application/json",
    };
    const url = `${supabaseUrl}/rest/v1/narrative_scene_entity_links?project_id=eq.${projectId}&select=entity_id`;
    const res = await fetch(url, { headers });
    if (!res.ok) return [];
    const data = await res.json();
    return Array.isArray(data) ? data : [];
  } catch {
    return [];
  }
}

/* ─────────────────────────────────────────────────────────────────
   Axis 1: Narrative Structure Convergence
   ───────────────────────────────────────────────────────────────── */

function check1A_BeatCountConsistency(
  storyOutline: any,
  beatSheet: any
): NarrativeStructureFinding | null {
  const storyBeats = storyOutline?.beats || storyOutline?.entries || [];
  const sheetBeats = beatSheet?.beats || beatSheet?.entries || [];
  const storyCount = storyBeats.length;
  const sheetCount = sheetBeats.length;
  const threshold = Math.round(storyCount * 0.8);

  if (sheetCount < threshold) {
    const missing = storyBeats
      .filter((sb: any) => !sheetBeats.some((bb: any) => (bb.name || bb.title) === (sb.name || sb.title)))
      .map((b: any) => `Beat ${b.number}: ${b.name || b.title}`);
    return {
      checkId: "1A-beat-count",
      severity: "high",
      upstreamDoc: "story_outline",
      downstreamDoc: "beat_sheet",
      description: `beat_sheet has ${sheetCount} beats, story_outline has ${storyCount}. Below 80% threshold (${threshold}). ${missing.length} story beats missing from beat_sheet.`,
      divergenceType: "omission",
      affectedElements: missing.slice(0, 5),
    };
  }
  return null;
}

function check1B_BeatNameConsistency(
  storyOutline: any,
  beatSheet: any
): NarrativeStructureFinding[] {
  const findings: NarrativeStructureFinding[] = [];
  const storyBeats = storyOutline?.beats || storyOutline?.entries || [];
  const sheetBeats = beatSheet?.beats || beatSheet?.entries || [];

  for (const sb of storyBeats) {
    const matchingSheetBeat = sheetBeats.find(
      (bb: any) => (bb.name || bb.title || "").toLowerCase() === (sb.name || sb.title || "").toLowerCase()
    );
    if (!matchingSheetBeat) continue;

    // Check if key entities from story outline beat description are missing in sheet beat
    const storyEntities = extractKeyEntities(sb.description);
    const sheetEntities = extractKeyEntities(matchingSheetBeat.description);
    const missing = storyEntities.filter(e => !sheetEntities.includes(e));

    if (missing.length > storyEntities.length * 0.5 && missing.length >= 2) {
      findings.push({
        checkId: "1B-beat-name",
        severity: "medium",
        upstreamDoc: "story_outline",
        downstreamDoc: "beat_sheet",
        description: `Beat "${sb.name}" in beat_sheet is missing key entities from story_outline: ${missing.join(", ")}`,
        divergenceType: "omission",
        affectedElements: missing,
      });
    }
  }
  return findings;
}

function check1C_ActStructurePreservation(
  treatment: any,
  beatSheet: any
): NarrativeStructureFinding[] {
  const findings: NarrativeStructureFinding[] = [];
  if (!treatment || !beatSheet) return findings;

  // Handle nested structure: { treatment: { treatment_narrative: "..." } }
  const treatmentObj = typeof treatment === 'object' && !Array.isArray(treatment)
    ? (treatment.treatment_narrative ? treatment.treatment_narrative : treatment)
    : treatment;

  // If treatment is a plain text string, use the whole text as a single section check
  if (typeof treatmentObj === 'string') {
    const treatmentText = treatmentObj;
    const treatmentEntities = extractKeyEntities(treatmentText).slice(0, 10);
    const sheetBeats = beatSheet.beats || beatSheet.entries || [];
    let foundInBeats = 0;
    for (const entity of treatmentEntities) {
      if ((sheetBeats as any[]).some((bb: any) => (bb.description || "").toUpperCase().includes(entity))) {
        foundInBeats++;
      }
    }
    if (foundInBeats < treatmentEntities.length * 0.3 && treatmentEntities.length >= 3) {
      findings.push({
        checkId: "1C-act-structure-full",
        severity: "medium",
        upstreamDoc: "treatment",
        downstreamDoc: "beat_sheet",
        description: `Treatment text has ${treatmentEntities.length} key entities, but only ${foundInBeats} appear in beat_sheet. Low cross-coverage may indicate structural drift.`,
        divergenceType: "omission",
        affectedElements: treatmentEntities.slice(0, 5),
      });
    }
    return findings;
  }

  // Structured act fields
  const actSections = [
    { key: "act_1", name: "Act 1" },
    { key: "act_2a", name: "Act 2A" },
    { key: "midpoint", name: "Midpoint" },
    { key: "act_2b", name: "Act 2B" },
    { key: "act_3", name: "Act 3" },
  ];

  for (const act of actSections) {
    const actText = treatmentObj[act.key];
    if (!actText) continue;

    const actEntities = extractKeyEntities(String(actText));
    if (actEntities.length === 0) continue;

    const sheetBeats = beatSheet.beats || beatSheet.entries || [];
    let foundInBeats = 0;
    for (const entity of actEntities.slice(0, 5)) {
      if ((sheetBeats as any[]).some((bb: any) => (bb.description || "").toUpperCase().includes(entity))) {
        foundInBeats++;
      }
    }

    if (foundInBeats === 0 && actEntities.length >= 2) {
      findings.push({
        checkId: `1C-act-structure-${act.key}`,
        severity: "high",
        upstreamDoc: "treatment",
        downstreamDoc: "beat_sheet",
        description: `${act.name} content in treatment has no corresponding representation in beat_sheet.`,
        divergenceType: "omission",
        affectedElements: actEntities.slice(0, 3),
      });
    }
  }
  return findings;
}

function check1D_CharacterArcConsistency(
  conceptBrief: any,
  beatSheet: any
): NarrativeStructureFinding[] {
  const findings: NarrativeStructureFinding[] = [];
  if (!conceptBrief || !beatSheet) return findings;

  // Extract character names from concept_brief.premise
  const premise = conceptBrief.premise || conceptBrief.logline || "";
  const cbCharacters = extractKeyEntities(premise).slice(0, 8);

  const sheetBeats = beatSheet.beats || beatSheet.entries || [];
  const sheetText = (sheetBeats as any[]).map((b: any) => b.description || b.title || "").join(" ").toUpperCase();

  for (const char of cbCharacters) {
    if (!sheetText.includes(char)) {
      findings.push({
        checkId: "1D-character-arc",
        severity: "medium",
        upstreamDoc: "concept_brief",
        downstreamDoc: "beat_sheet",
        description: `Character "${char}" appears in concept_brief premise but has no mention in beat_sheet.`,
        divergenceType: "omission",
        affectedElements: [char],
      });
    }
  }
  return findings;
}

function check1E_MidpointConvergence(
  treatment: any,
  beatSheet: any
): NarrativeStructureFinding | null {
  if (!treatment || !beatSheet) return null;

  // Handle nested structure: { treatment: { treatment_narrative: "..." } }
  let treatmentMidpoint: string = "";
  if (treatment.midpoint) {
    treatmentMidpoint = treatment.midpoint;
  } else if (treatment.treatment?.treatment_narrative) {
    // Plain text treatment — skip midpoint check (no structured midpoint)
    return null;
  }

  if (!treatmentMidpoint) return null;

  const treatmentEntities = extractKeyEntities(treatmentMidpoint);
  if (treatmentEntities.length === 0) return null;

  const sheetBeats = beatSheet.beats || beatSheet.entries || [];
  // Find midpoint beat: name contains "midpoint" or page range around 55-70
  const midpointBeat = sheetBeats.find((b: any) => {
    const nameMatch = b.name?.toLowerCase().includes("midpoint");
    const pageMatch = b.page_range && (() => {
      const page = parseInt(b.page_range.split("-")[0]);
      return page >= 55 && page <= 70;
    })();
    return nameMatch || pageMatch;
  });

  if (!midpointBeat) {
    return {
      checkId: "1E-midpoint",
      severity: "critical",
      upstreamDoc: "treatment",
      downstreamDoc: "beat_sheet",
      description: `treatment.midpoint is defined but beat_sheet has no midpoint beat.`,
      divergenceType: "omission",
      affectedElements: treatmentEntities.slice(0, 3),
    };
  }

  const beatEntities = extractKeyEntities(midpointBeat.description);
  const missing = treatmentEntities.filter(e => !beatEntities.includes(e));
  const contradictions = beatEntities.filter(e => !treatmentEntities.includes(e) && e.length > 3);

  if (missing.length > 0 || contradictions.length > 2) {
    return {
      checkId: "1E-midpoint",
      severity: "critical",
      upstreamDoc: "treatment",
      downstreamDoc: "beat_sheet",
      description: `beat_sheet midpoint beat "${midpointBeat.name}" diverges from treatment.midpoint. Missing: ${missing.join(", ")}. New: ${contradictions.join(", ")}.`,
      divergenceType: missing.length > contradictions.length ? "omission" : "contradiction",
      affectedElements: [...missing, ...contradictions].slice(0, 5),
    };
  }

  return null;
}

/* ─────────────────────────────────────────────────────────────────
   Axis 2: Feasibility Convergence
   ───────────────────────────────────────────────────────────────── */

function check2A_EntityPresenceConsistency(
  entities: any[],
  entityLinks: any[]
): FeasibilityFinding[] {
  const findings: FeasibilityFinding[] = [];

  for (const entity of entities) {
    if (entity.entity_type !== "character") continue;
    const actualCount = entityLinks.filter(l => l.entity_id === entity.id).length;
    if (entity.scene_count !== actualCount) {
      findings.push({
        checkId: "2A-entity-presence",
        severity: "medium",
        entityOrSystem: entity.canonical_name,
        description: `narrative_entities.scene_count=${entity.scene_count}, actual links=${actualCount}`,
        expected: String(actualCount),
        actual: String(entity.scene_count),
      });
    }
  }
  return findings;
}

function check2B_CharacterPopulationCompleteness(
  _entities: any[],
  _entityLinks: any[],
  _sceneGraph: any,
  _supabaseUrl: string,
  _serviceRoleKey: string,
  _projectId: string
): FeasibilityFinding[] {
  // Synchronous stub — see check2B_viaREST below for async implementation
  return [];
}

/**
 * check2B — entity population completeness check.
 * Fetches data via direct REST API to avoid supabase client field-mapping issues.
 * Computes orphaned link counts by checking if linked entity IDs exist in narrative_entities.
 */
async function check2B_viaREST(
  supabaseUrl: string,
  serviceRoleKey: string,
  projectId: string
): Promise<FeasibilityFinding[]> {
  const findings: FeasibilityFinding[] = [];

  try {
    const headers = {
      apikey: serviceRoleKey,
      Authorization: `Bearer ${serviceRoleKey}`,
      "Content-Type": "application/json",
    };

    // 1. Get all distinct entity_ids from links
    const linksRes = await fetch(
      `${supabaseUrl}/rest/v1/narrative_scene_entity_links?project_id=eq.${projectId}&select=entity_id`,
      { headers }
    );
    const linksJson = await linksRes.json();
    if (!Array.isArray(linksJson)) return findings;
    const allLinkedIds = [...new Set(linksJson.map((l: any) => l.entity_id).filter(Boolean))];
    if (allLinkedIds.length === 0) return findings;

    // 2. Get character entity IDs
    const charRes = await fetch(
      `${supabaseUrl}/rest/v1/narrative_entities?project_id=eq.${projectId}&entity_type=eq.character&select=id,canonical_name`,
      { headers }
    );
    const charData: Array<{ id: string; canonical_name: string }> = await charRes.json();

    // 3. Get location entity IDs
    const locRes = await fetch(
      `${supabaseUrl}/rest/v1/narrative_entities?project_id=eq.${projectId}&entity_type=eq.location&select=id`,
      { headers }
    );
    const locData: Array<{ id: string }> = await locRes.json();

    const charIdSet = new Set(charData.map(e => e.id));
    const locIdSet = new Set(locData.map(e => e.id));

    let orphanedCharCount = 0;
    for (const id of allLinkedIds) {
      if (!charIdSet.has(id) && !locIdSet.has(id)) {
        orphanedCharCount++;
      }
    }

    if (orphanedCharCount > 0) {
      findings.push({
        checkId: "2B-character-population",
        severity: orphanedCharCount > 30 ? "high" : "medium",
        entityOrSystem: "character population",
        description: `${orphanedCharCount} links in narrative_scene_entity_links reference entity IDs not in narrative_entities (orphaned — pre-dedup data or entity extraction gap)`,
        expected: "All links resolve to narrative_entities records",
        actual: `${orphanedCharCount} orphaned links`,
      });
    }

    // 4. Phantom characters: character entities with no links
    const linkedRes = await fetch(
      `${supabaseUrl}/rest/v1/narrative_scene_entity_links?project_id=eq.${projectId}&entity_id=in.(${charData.map(e => e.id).join(',')})&select=entity_id`,
      { headers }
    );
    const linkedJson: Array<{ entity_id: string }> = await linkedRes.json();
    const linkedCharIdSet = new Set(linkedJson.map(l => l.entity_id).filter(Boolean));
    const phantomChars = charData.filter(e => !linkedCharIdSet.has(e.id));

    if (phantomChars.length > 0) {
      findings.push({
        checkId: "2B-phantom-characters",
        severity: "low",
        entityOrSystem: "phantom characters",
        description: `${phantomChars.length} character entities in narrative_entities have no scene links`,
        expected: "All narrative character entities appear in scene links",
        actual: phantomChars.map(e => e.canonical_name).join(", ").slice(0, 80),
      });
    }

  } catch(err) {
    console.error("[check2B_viaREST] error:", String(err));
  }

  return findings;
}


function check2C_LocationFeasibility(
  sceneGraph: any
): FeasibilityFinding[] {
  const findings: FeasibilityFinding[] = [];
  if (!sceneGraph?.scenes?.length) return findings;

  const allLocations: string[] = [];
  for (const scene of sceneGraph.scenes) {
    // location field is a single string (from scene_graph_versions.location)
    const loc = (scene.location as string) || "";
    if (loc) {
      // Normalise: "VARIOUS LOCATIONS" stays as-is; "NEPALESE MOUNTAINS" stays
      allLocations.push(loc.toUpperCase());
    }
    // Fallback: parse from slugline
    if (!loc && scene.slugline) {
      const parts = scene.slugline.split(/\s*[.-]\s*/);
      if (parts.length >= 2) {
        allLocations.push(parts[1].replace(/^(INT|EXT|EST|INT\/EXT|I\/E)\.\s*/i, "").trim().toUpperCase());
      }
    }
  }

  if (allLocations.length === 0) return findings;

  const uniqueLocations = [...new Set(allLocations.map(l => l.toUpperCase()))];
  const locationCounts = countOccurrences(allLocations.map(l => l.toUpperCase()));
  const recurringLocations = Object.entries(locationCounts).filter(([, count]) => count >= 3).length;
  const oneOffLocations = Object.entries(locationCounts).filter(([, count]) => count === 1).length;

  let complexity: "low" | "medium" | "high" = "low";
  if (uniqueLocations.length > 15 || (uniqueLocations.length > 10 && oneOffLocations > recurringLocations)) {
    complexity = "high";
  } else if (uniqueLocations.length > 5) {
    complexity = "medium";
  }

  findings.push({
    checkId: "2C-location-feasibility",
    severity: complexity === "high" ? "high" : "low",
    entityOrSystem: "location_cost",
    description: `${uniqueLocations.length} unique locations, ${recurringLocations} recurring (≥3 uses), ${oneOffLocations} one-offs → production complexity: ${complexity}`,
    expected: complexity !== "high" ? "≤15 unique locations or ≥recurring ≥one-offs" : "high one-off location count — budget risk",
    actual: `complexity: ${complexity}`,
  });

  return findings;
}

function check2D_DayNightDistribution(
  sceneGraph: any
): FeasibilityFinding[] {
  const findings: FeasibilityFinding[] = [];
  if (!sceneGraph?.scenes?.length) return findings;

  const timeOfDayCounts: Record<string, number> = {};
  for (const scene of sceneGraph.scenes) {
    const tod = (scene.time_of_day as string) || "unknown";
    timeOfDayCounts[tod] = (timeOfDayCounts[tod] || 0) + 1;
  }

  const total = sceneGraph.scenes.length;
  const nightCount = (timeOfDayCounts["night"] || timeOfDayCounts["NIGHT"] || 0) +
    Object.entries(timeOfDayCounts)
      .filter(([k]) => k.toLowerCase().includes("night"))
      .reduce((acc, [, v]) => acc + v, 0);

  // Count more broadly
  let nightTotal = 0;
  for (const [key, count] of Object.entries(timeOfDayCounts)) {
    if (key.toLowerCase().includes("night") || key.toLowerCase() === "dark") {
      nightTotal += count;
    }
  }

  const nightRatio = nightTotal / total;

  if (nightRatio > 0.6) {
    findings.push({
      checkId: "2D-day-night",
      severity: "medium",
      entityOrSystem: "shoot_schedule",
      description: `${nightTotal}/${total} scenes (${Math.round(nightRatio * 100)}%) are night scenes — night-shoot premium flag. Raw time_of_day distribution: ${JSON.stringify(timeOfDayCounts)}`,
      expected: "≤60% night scenes for standard shoot economics",
      actual: `${Math.round(nightRatio * 100)}% night scenes`,
    });
  }

  return findings;
}

function check2E_SceneCountVsBeatCount(
  sceneGraph: any,
  beatSheet: any
): FeasibilityFinding[] {
  const findings: FeasibilityFinding[] = [];
  if (!sceneGraph?.scenes?.length) return findings;

  const sceneCount = sceneGraph.scenes.length;
  const beatCount = (beatSheet?.beats || beatSheet?.entries || []).length;
  if (beatCount === 0) return findings;

  if (sceneCount < beatCount) {
    findings.push({
      checkId: "2E-scene-beat-ratio",
      severity: "high",
      entityOrSystem: "scene_count",
      description: `${sceneCount} scenes for ${beatCount} beats — some beats have no script content`,
      expected: "scene_count ≥ beat_count",
      actual: `scene_count (${sceneCount}) < beat_count (${beatCount})`,
    });
  } else if (sceneCount > beatCount * 4) {
    findings.push({
      checkId: "2E-scene-beat-ratio",
      severity: "medium",
      entityOrSystem: "scene_count",
      description: `${sceneCount} scenes for ${beatCount} beats — ratio >4:1, unusually high`,
      expected: "scene_count ≤ beat_count × 4",
      actual: `${sceneCount} scenes for ${beatCount} beats`,
    });
  }

  return findings;
}

function check2F_CastSizeFeasibility(
  entities: any[],
  entityLinks: any[],
  conceptBrief: any
): FeasibilityFinding[] {
  const findings: FeasibilityFinding[] = [];

  const linkedEntityIds = [...new Set(entityLinks.map(l => l.entity_id))];
  const characters = entities.filter(e =>
    e.entity_type === "character" && linkedEntityIds.includes(e.id)
  );
  const castSize = characters.length;

  const rating = conceptBrief?.rating || conceptBrief?.target_rating || conceptBrief?.target_audience || "PG-13";
  const upperRating = rating.toUpperCase();

  let maxRecommended = 30;
  if (upperRating.includes("R")) maxRecommended = 50;
  else if (upperRating.includes("PG-13") || upperRating.includes("PG13")) maxRecommended = 30;
  else if (upperRating.includes("PG")) maxRecommended = 25;
  else if (upperRating.includes("G")) maxRecommended = 20;

  if (castSize > maxRecommended * 1.2) {
    findings.push({
      checkId: "2F-cast-size",
      severity: castSize > maxRecommended * 1.5 ? "high" : "medium",
      entityOrSystem: "cast_size",
      description: `${castSize} speaking characters exceeds ${rating} guidance (${maxRecommended} recommended). Production infeasibility risk.`,
      expected: `≤${maxRecommended} characters for ${rating}`,
      actual: `${castSize} characters`,
    });
  }

  return findings;
}

/* ─────────────────────────────────────────────────────────────────
   LLM Prescription Enhancer — Phase 2.2
   ───────────────────────────────────────────────────────────────── */

/**
 *enhancePrescriptionsWithLLM
 *
 * Takes the deterministic findings already generated by convergence-coach-engine,
 * then uses an LLM to transform generic "Review and align..." prescriptions into
 * scene-anchored, content-specific prescriptions with estimated GP impact.
 *
 * Architecture: LLM augments deterministic checks — it generates actionable
 * guidance for findings that were DETECTED structurally. It never invents findings.
 * Falls back to the original deterministic prescription on any error.
 */
async function enhancePrescriptionsWithLLM(
  supabaseUrl: string,
  serviceRoleKey: string,
  findings: Array<{ severity: string; description: string; checkId: string; axis: string; affectedElements?: string[] }>,
  beatSheet: any,
  sceneGraph: any,
  conceptBrief: any
): Promise<Array<{ finding: any; scene_prescription?: string; estimated_gp_impact?: number }>> {
  // Only process critical + high findings (highest leverage)
  const priorityFindings = findings.filter(f => f.severity === 'critical' || f.severity === 'high');
  if (priorityFindings.length === 0) return [];

  // Build scene context for the LLM
  const scenes = (sceneGraph?.scenes || []).slice(0, 60);
  const beats = (beatSheet?.beats || beatSheet?.entries || []).slice(0, 60);

  const sceneIndex = scenes.map((s: any, i: number) =>
    `[Scene ${i + 1}] ${s.slugline || 'Unknown'}: ${(s.content || '').slice(0, 200).replace(/\n/g, ' ').trim()}`
  ).join('\n');

  const beatIndex = beats.map((b: any, i: number) =>
    `[Beat ${b.number || i + 1}] ${b.name || b.title || 'Untitled'}: ${(b.description || '').slice(0, 150).replace(/\n/g, ' ').trim()}`
  ).join('\n');

  const findingList = priorityFindings.map((f, i) =>
    `${i + 1}. [${f.checkId}] ${f.description} (severity: ${f.severity})`
  ).join('\n');

  const systemPrompt = `You are a script consultant embedded in a production tool called IFFY. You are reviewing a screenplay's convergence diagnostic.

The deterministic convergence engine has already DETECTED the following issues. Your job is to:
1. Identify which SCENE(s) in the script each finding applies to
2. Generate a SCENE-SPECIFIC, ACTIONABLE prescription — not a generic directive
3. Estimate the GP (screenplay quality) impact on a 0–20 scale if this prescription is applied

RULES:
- You generate prescriptions for scenes that EXIST in the index. Do not hallucinate scene numbers.
- If a finding is structural/narrative-wide (e.g., missing midpoint beat, act structure drift), anchor the prescription to the most relevant specific scene and note it's structural.
- NEVER invent findings not present in the deterministic findings list.
- Format: Return valid JSON array [{"sceneSlugline": "...", "prescription": "...", "estimated_gp_impact": 0.12}, ...]
- prescription must be a concrete action: "In Scene 40, BILL receives MARCUS's threat passively — add a decision point where he secretly records the exchange"
- estimated_gp_impact is a decimal 0–20, representing expected screenplay quality improvement (e.g., 0.12 means +12 hundredths of a GP point)
- If a finding applies to no specific scene (broad structural), use sceneSlugline: "structural"
- Maximum 8 prescriptions (prioritise highest-severity findings)
- Do NOT output anything other than the JSON array`;

  const userPrompt = `CONVERGENCE FINDINGS TO PRESCRIBE:
${findingList}

SCRIPT SCENE INDEX (first 60 scenes):
${sceneIndex || 'No scenes available'}

BEAT SHEET INDEX (first 60 beats):
${beatIndex || 'No beats available'}

Generate scene-specific prescriptions for each finding above.`;

  try {
    // Use the same AI gateway pattern as dev-engine-v2
    const apiKey = Deno.env.get('LOVABLE_API_KEY') || Deno.env.get('OPENROUTER_API_KEY') || '';
    if (!apiKey) return []; // No AI key = fall back to deterministic only

    const response = await fetch('https://ai-gateway.woz-ai.com/v1/messages', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'Authorization': `Bearer ${apiKey}`,
        'x-ai-provider': 'openrouter',
      },
      body: JSON.stringify({
        model: 'google/gemini-2.5-flash',
        messages: [
          { role: 'system', content: systemPrompt },
          { role: 'user', content: userPrompt },
        ],
        max_tokens: 4000,
        temperature: 0.2,
      }),
    });

    if (!response.ok) {
      console.error('[enhancePrescriptionsWithLLM] AI gateway returned', response.status);
      return [];
    }

    const result = await response.json() as any;
    const text = result?.choices?.[0]?.message?.content || '';
    // Extract JSON from the response
    const jsonMatch = text.match(/\[\s*\{[\s\S]*\}\s*\]/);
    if (!jsonMatch) {
      console.error('[enhancePrescriptionsWithLLM] No JSON found in response');
      return [];
    }

    const parsed = JSON.parse(jsonMatch[0]) as Array<{ sceneSlugline: string; prescription: string; estimated_gp_impact: number }>;
    return parsed.map(p => ({
      sceneSlugline: p.sceneSlugline,
      prescription: p.prescription,
      estimated_gp_impact: p.estimated_gp_impact,
    }));
  } catch (err) {
    console.error('[enhancePrescriptionsWithLLM] failed:', String(err));
    return []; // Non-blocking fallback
  }
}

/* ─────────────────────────────────────────────────────────────────
   Prescription generator (deterministic — Phase 2.1)
   ───────────────────────────────────────────────────────────────── */

function generatePrescriptions(
  nsFindings: NarrativeStructureFinding[],
  feasFindings: FeasibilityFinding[],
  blockers: Blocker[],
  fixable: FixableIssue[]
): RevisionPrescription[] {
  const prescriptions: RevisionPrescription[] = [];
  let priority = 1;

  // Critical blockers first
  for (const blocker of blockers) {
    prescriptions.push({
      axis: blocker.axis,
      priority: priority++,
      prescription: `BLOCKER: ${blocker.cannotFixWithout}`,
      whyItMatters: blocker.description,
      upstreamChange: blocker.upstreamSource,
    });
  }

  // Sort findings by severity
  const allFindings = [
    ...nsFindings.map(f => ({ ...f, axis: "narrative_structure" as const })),
    ...feasFindings.map(f => ({ ...f, axis: "feasibility" as const })),
  ];
  allFindings.sort((a, b) => {
    const sOrder = { critical: 0, high: 1, medium: 2, low: 3 };
    return (sOrder[a.severity] ?? 2) - (sOrder[b.severity] ?? 2);
  });

  for (const finding of allFindings) {
    let fixBy: string | null = null;
    if (finding.axis === "narrative_structure") {
      const f = finding as NarrativeStructureFinding;
      if (f.upstreamDoc === "story_outline" || f.divergenceType === "omission") {
        fixBy = "Regenerate beat_sheet to match story_outline structure";
      } else {
        fixBy = "Review and align beat_sheet with upstream document";
      }
    } else {
      const f = finding as FeasibilityFinding;
      if (f.checkId.startsWith("2A") || f.checkId.startsWith("2B")) {
        fixBy = "Rerun entity linking pipeline to sync entity counts";
      } else {
        fixBy = "Review feasibility constraints in concept brief or scene graph";
      }
    }

    prescriptions.push({
      axis: finding.axis,
      priority: priority++,
      prescription: fixBy,
      whyItMatters: finding.description,
      upstreamChange: null,
    });
  }

  return prescriptions;
}

/* ─────────────────────────────────────────────────────────────────
   Main handler
   ───────────────────────────────────────────────────────────────── */

serve(async (req: Request) => {
  if (req.method === "OPTIONS") {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const { projectId, axes } = await req.json();

    if (!projectId) {
      return new Response(JSON.stringify({ error: "projectId is required" }), {
        status: 400,
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    // Service role client — reads all data
    const supabase = createClient(
      Deno.env.get("SUPABASE_URL") ?? "",
      Deno.env.get("SUPABASE_SERVICE_ROLE_KEY") ?? "",
    );

    // ── Fetch all canonical data ──
    const [
      beatSheetVersion,
      storyOutlineVersion,
      treatmentVersion,
      conceptBriefVersion,
      sceneGraph,
      entities,
      entityLinks,
    ] = await Promise.all([
      fetchLatestDocVersion(supabase, projectId, "beat_sheet"),
      fetchLatestDocVersion(supabase, projectId, "story_outline"),
      fetchLatestDocVersion(supabase, projectId, "treatment"),
      fetchLatestDocVersion(supabase, projectId, "concept_brief"),
      fetchSceneGraph(
        Deno.env.get("SUPABASE_URL") ?? "",
        Deno.env.get("SUPABASE_SERVICE_ROLE_KEY") ?? "",
        projectId
      ),
      fetchNarrativeEntities(
        Deno.env.get("SUPABASE_URL") ?? "",
        Deno.env.get("SUPABASE_SERVICE_ROLE_KEY") ?? "",
        projectId
      ),
      fetchEntityLinks(
        Deno.env.get("SUPABASE_URL") ?? "",
        Deno.env.get("SUPABASE_SERVICE_ROLE_KEY") ?? "",
        projectId
      ),
    ]);

    const beatSheet = beatSheetVersion ? extractDocContent(beatSheetVersion) : null;
    const storyOutline = storyOutlineVersion ? extractDocContent(storyOutlineVersion) : null;
    const treatment = treatmentVersion ? extractDocContent(treatmentVersion) : null;
    const conceptBrief = conceptBriefVersion ? extractDocContent(conceptBriefVersion) : null;

    // ── Axis 1: Narrative Structure ──
    const nsFindings: NarrativeStructureFinding[] = [];
    let nsStatus: "converged" | "diverged" | "unknown" = "unknown";
    let nsScore = 1.0;

    const runNarrativeStructure = !axes || axes.includes("narrative_structure");

    if (runNarrativeStructure) {
      if (!beatSheet || !storyOutline || !treatment) {
        nsStatus = "unknown";
        nsScore = 0;
      } else {
        const finding1A = check1A_BeatCountConsistency(storyOutline, beatSheet);
        if (finding1A) nsFindings.push(finding1A);

        nsFindings.push(...check1B_BeatNameConsistency(storyOutline, beatSheet));
        nsFindings.push(...check1C_ActStructurePreservation(treatment, beatSheet));
        nsFindings.push(...check1D_CharacterArcConsistency(conceptBrief, beatSheet));

        const finding1E = check1E_MidpointConvergence(treatment, beatSheet);
        if (finding1E) nsFindings.push(finding1E);

        nsStatus = nsFindings.length === 0 ? "converged" : "diverged";
        nsScore = scoreFindings(nsFindings);
      }
    }

    // ── Axis 2: Feasibility ──
    const feasFindings: FeasibilityFinding[] = [];
    let feasStatus: "converged" | "diverged" | "unknown" = "unknown";
    let feasScore = 1.0;

    const runFeasibility = !axes || axes.includes("feasibility");

    if (runFeasibility) {
      // Run whatever checks we can with available data.
      // scene_graph may be unavailable due to RLS even with service role — degrade gracefully.
      feasFindings.push(...check2A_EntityPresenceConsistency(entities, entityLinks));
      feasFindings.push(...check2F_CastSizeFeasibility(entities, entityLinks, conceptBrief));

      if (sceneGraph?.scenes?.length) {
        feasFindings.push(...await check2B_viaREST(
          Deno.env.get("SUPABASE_URL") ?? "",
          Deno.env.get("SUPABASE_SERVICE_ROLE_KEY") ?? "",
          projectId
        ));
        feasFindings.push(...check2C_LocationFeasibility(sceneGraph));
        feasFindings.push(...check2D_DayNightDistribution(sceneGraph));
        feasFindings.push(...check2E_SceneCountVsBeatCount(sceneGraph, beatSheet));
      }

      if (entities.length === 0 && !sceneGraph?.scenes?.length) {
        feasStatus = "unknown";
        feasScore = 0;
      } else {
        feasStatus = feasFindings.length === 0 ? "converged" : "diverged";
        feasScore = scoreFindings(feasFindings);
      }
    }

    // ── Blockers and fixable ──
    const blockers: Blocker[] = [];
    const fixable: FixableIssue[] = [];

    for (const f of nsFindings) {
      if (f.severity === "critical" && f.upstreamDoc !== "beat_sheet") {
        blockers.push({
          axis: "narrative_structure",
          description: f.description,
          upstreamSource: f.upstreamDoc,
          cannotFixWithout: `${f.upstreamDoc} must be corrected before beat_sheet can converge`,
        });
      } else {
        fixable.push({
          axis: "narrative_structure",
          description: f.description,
          fixBy: "regenerate_beat_sheet",
          estimatedEffort: "medium",
        });
      }
    }

    for (const f of feasFindings) {
      if (f.checkId === "2B-character-population") {
        fixable.push({
          axis: "feasibility",
          description: f.description,
          fixBy: "rerun_entity_links",
          estimatedEffort: "medium",
        });
      } else {
        fixable.push({
          axis: "feasibility",
          description: f.description,
          fixBy: "regenerate_beat_sheet",
          estimatedEffort: "medium",
        });
      }
    }

    // ── Convergence trajectory ──
    const criticalCount = [...nsFindings, ...feasFindings].filter(f => f.severity === "critical").length;
    let trend: "improving" | "stable" | "degrading" | "unknown" = "unknown";
    let trendReason = "Insufficient historical data for trend analysis";

    if (nsStatus === "converged" && feasStatus === "converged") {
      trend = "stable";
      trendReason = "All convergence axes are currently converged";
    } else if (criticalCount >= 2) {
      trend = "degrading";
      trendReason = `${criticalCount} critical findings indicate active narrative drift`;
    } else if (nsFindings.length > 0 || feasFindings.length > 0) {
      trend = "degrading";
      trendReason = `${nsFindings.length + feasFindings.length} convergence issues found — drift is occurring`;
    } else {
      trend = "stable";
      trendReason = "No convergence issues detected";
    }

    // ── Prescriptions ──
    const revisionPrescriptions = generatePrescriptions(nsFindings, feasFindings, blockers, fixable);

    // ── Phase 2.2: LLM scene-anchored prescription enhancement ──
    // Run in background — does not block the diagnostic response.
    // Augments deterministic prescriptions with scene-specific actionable guidance + GP impact.
    if (Deno.env.get('LOVABLE_API_KEY') || Deno.env.get('OPENROUTER_API_KEY')) {
      try {
        const allFindings = [
          ...nsFindings.map(f => ({ ...f, axis: 'narrative_structure' as const, affectedElements: f.affectedElements || [] })),
          ...feasFindings.map(f => ({ ...f, axis: 'feasibility' as const, affectedElements: [f.entityOrSystem] })),
        ];
        const llmEnhanced = await enhancePrescriptionsWithLLM(
          Deno.env.get('SUPABASE_URL') ?? '',
          Deno.env.get('SUPABASE_SERVICE_ROLE_KEY') ?? '',
          allFindings,
          beatSheet,
          sceneGraph,
          conceptBrief
        );

        // Merge LLM prescriptions into revisionPrescriptions
        if (llmEnhanced.length > 0) {
          for (const enhanced of llmEnhanced) {
            // Find the prescription with the matching finding (by priority index)
            const idx = revisionPrescriptions.findIndex(p => {
              // Match by severity and position in list
              return true; // Already ordered by severity in generatePrescriptions
            });
            // Attach scene_prescription to highest-severity unmatched prescriptions
            // Simple merge: pair in order (findings are sorted by severity already)
          }
          // Simpler approach: inject scene_prescription into prescriptions by position
          for (let i = 0; i < revisionPrescriptions.length && i < llmEnhanced.length; i++) {
            revisionPrescriptions[i].scene_prescription = llmEnhanced[i].prescription;
            revisionPrescriptions[i].estimated_gp_impact = llmEnhanced[i].estimated_gp_impact;
          }
        }
      } catch (e) {
        console.error('[convergence-coach] LLM enhancement failed (non-blocking):', String(e));
      }
    }

    // ── Assemble response ──
    const diagnostic: ConvergenceDiagnostic = {
      projectId,
      generatedAt: new Date().toISOString(),
      narrativeStructureAxis: {
        status: nsStatus,
        score: Math.round(nsScore * 100) / 100,
        findings: nsFindings,
      },
      feasibilityAxis: {
        status: feasStatus,
        score: Math.round(feasScore * 100) / 100,
        findings: feasFindings,
      },
      convergenceTrajectory: {
        trend,
        trendReason,
        blockers,
        fixable,
      },
      revisionPrescriptions,
    };

    return new Response(JSON.stringify(diagnostic), {
      headers: { ...corsHeaders, "Content-Type": "application/json" },
    });

  } catch (err: any) {
    return new Response(JSON.stringify({ error: err.message }), {
      status: 500,
      headers: { ...corsHeaders, "Content-Type": "application/json" },
    });
  }
});
