UPDATE project_canon
SET canon_json = (
  COALESCE(canon_json, '{}'::jsonb) || jsonb_build_object(
    'logline', 'A wealthy bride-to-be is kidnapped before her wedding, only to discover her captor is actually protecting her from those who orchestrated her abduction, including her fiancé, leading to an unexpected and dangerous romance.',
    'premise', 'Leila Arman, a wealthy bride, is kidnapped just days before her wedding. Her captor, Gabriel Varela, is not the panicked criminal she expects, but a hardened man who seems intent on keeping her alive. As they evade those who want her silenced, Leila realizes her fiancé and his associates are behind the plot, and Gabriel is her only protector.',
    'title', 'My Fiancé Paid the Ransom',
    'tone_style', 'High-heat thriller-romance, characterized by relentless cliffhangers and a sense of constant danger. Gritty and tense, moving through curated hideouts and improvised locations. Active understatement — loaded glances, subtle gestures, sharp concise dialogue.',
    'genres', '["Thriller", "Romance"]'::jsonb,
    'world_rules', '["The kidnapping is a setup orchestrated by Leila''s fiancé and his associates.", "The ransom is a cover for a plan to silence Leila permanently.", "Gabriel Varela is not a typical kidnapper; he is protecting Leila.", "Leila''s rescue is a trap.", "Trust is a dangerous and shifting commodity.", "The wrong man is the only one who can keep Leila alive.", "The world is a high-stakes game of cat and mouse where information is scarce and every interaction could be a trap."]'::jsonb,
    'world_description', 'Contemporary urban setting. Confined spaces, abandoned warehouses, small sparsely furnished apartments, dense urban forest trails, secluded diners, derelict industrial complexes. Gritty tense atmosphere emphasizing claustrophobia and constant threat. Polished urban surfaces — glass, steel, clinical materials — contrasted with rough hideout textures.',
    'setting', 'Contemporary urban — luxury bridal suites, corporate towers, underground safe houses, improvised hideouts',
    'themes', '["The Shattering of Trust — betrayal from those closest", "Survival as Revelation — extreme circumstances strip away artifice", "The Allure of the Forbidden — dangerous connection born of crisis", "Redefining Family and Loyalty — severing old ties forging unexpected bonds", "Agency in Adversity — victim to strategic player"]'::jsonb,
    'characters', '[
      {"name": "Leila Arman", "role": "Protagonist", "description": "Mid-20s. Strikingly beautiful, elegant, almost fragile. Initial polished perfection — designer clothes, flawless makeup — frays under duress. Smudged makeup, torn clothing, raw desperate beauty. Delicate gold locket from grandmother.", "traits": "Highly intelligent, observant, quick-witted. Surprising resilience, adaptability under pressure. Fluent in several languages. Expert at reading people and understanding high society.", "backstory": "Born into immense wealth, family known for philanthropy and shadowy dealings. Life a gilded cage. Engagement to Julian a strategic alliance not love. Latent artistic sensibility expressed through sketching.", "goals": "Initially escape. Shifts to survival then uncovering truth of betrayal. Seeks to forge new identity free from control.", "secrets": "Family philanthropic facade hides shadowy dealings.", "relationships": "Hostile captor-captive bond with Gabriel evolving into intense attraction. Transactional relationship with Julian disguised as love."},
      {"name": "Gabriel Varela", "role": "Captor / Protector", "description": "Late 30s. Lean wiry strength honed by combat. Eyes the color of storm-lit steel. Practical dark clothing. Subtle scars. Distinctive jagged scar above left eye like lightning strike.", "traits": "Master of close-quarters combat, tactical evasion, surveillance. Laconic direct often gruff. Speaks only when necessary.", "backstory": "Former elite military intelligence dishonorably discharged. Now independent contractor in black market: extraction, protection. Strict personal code. Hired to kidnap Leila but discovered true intent was permanent silencing.", "goals": "Protect Leila and ensure survival. Driven by atonement and growing emotional attachment.", "secrets": "Past military failure that haunts him. Network of dangerous contacts.", "relationships": "Partnership forged in fire with Leila. Drawn to her innocence and resilience."},
      {"name": "Julian Thorne", "role": "Antagonist / Betrayer Fiancé", "description": "Early 30s. Impeccably groomed, handsome. Confident easy smile that rarely reaches his eyes. Expensive tailored suits. Projects effortless charm and authority.", "traits": "Master manipulator, brilliant strategist, incredibly persuasive. Deep connections in corporate political and criminal underworlds.", "backstory": "Heir to powerful corporate empire. Engagement to Leila a calculated move to merge assets and eliminate a rival.", "goals": "Consolidate power, eliminate threats, maintain public image. Values control and reputation above all.", "secrets": "History of quietly eliminating obstacles. Ransom is smokescreen for permanent silencing.", "relationships": "Views Leila as asset to be managed. His concern is performance."},
      {"name": "Anna", "role": "False Ally / Betrayer", "description": "Leila''s best friend, secretly working with Julian for personal gain driven by corrosive envy.", "traits": "Deceptive, envious, opportunistic. Support for Leila is a facade.", "backstory": "Driven by desire for share of Julian''s illicit wealth and envy of Leila''s privileged life.", "goals": "Personal gain through alliance with Julian at Leila''s expense.", "secrets": "Secret collaboration with the antagonist.", "relationships": "Presents as confidante while secretly undermining Leila."}
    ]'::jsonb,
    'locations', '["Luxury bridal suite — opulent pristine white lilies diamond engagement ring", "Abandoned warehouse — tense exchanges industrial decay", "Small sparsely furnished apartment — moments of vulnerability cramped intimacy", "Dense urban forest trail — high-stakes chase sequences", "Secluded diner — clandestine meetings", "Derelict industrial complex — climactic confrontations"]'::jsonb,
    'format_constraints', 'Vertical-drama format. 120-180 second episodes. 60 episodes. Beat every ~15 seconds. Relentless pacing with continuous beat cadence and high cliffhanger density.',
    'comparables', '[{"title": "The Night Agent", "platform": "Netflix", "note": "High-stakes thriller relentless pacing romantic connection under duress"}, {"title": "Mr. & Mrs. Smith", "note": "High-tension romantic thriller shifting loyalties"}, {"title": "The Firm", "note": "Protagonist discovers perfect life built on corruption"}, {"title": "You", "platform": "Netflix", "note": "Psychological suspense dark side of romance"}]'::jsonb
  )
)
WHERE project_id = '998f8ae7-b855-4670-9dfd-e6265d94b230';